appName: myProject
latestImage: v0.2.0
services:
  webapp:
    build:
      context: ./dir
      dockerfile: Dockerfile-alternate
      args:
        buildno: 1
  microservice: www.example.com/api
#  git tag v0.2.0